import type { Metadata } from "next";
import { Providers } from "./provider";

import "./globals.css";
import NavBar from "@/components/navBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className="">
          <NavBar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
